### ISSUE TITLE
Raspberry Pi3 with Debian ERROR: standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by EmilNachev** [jwigley/docker-smokeping-speedtest#2]
root@DietPi3:/usr/src/docker-smokeping-speedtest# docker run --name=smokeping-speedtest -p 9500:80 -e PUID=1000 -e PGID=1000 -e TZ=Europe/Sofia -v /tmp/docker-smokeping/data:/data -v /usr/src/docker-smokeping-speedtest/conf:/config --restart unless-stopped jwigley/smokeping-speedtest
Unable to find image 'jwigley/smokeping-speedtest:latest' locally
latest: Pulling from jwigley/smokeping-speedtest
c2cd537b3555: Pull complete
1770f0c349a4: Pull complete
2a0b715da3bb: Pull complete
3ac805142b2e: Pull complete
c33c5ec882b0: Pull complete
76a4b98438d3: Pull complete
9fa3420b41f6: Pull complete
442343c36852: Pull complete
999833e6614d: Pull complete
94e06dce22f2: Pull complete
Digest: sha256:a0e453e735bf5cd288df918b78774638eebb8c5cac057a7c906859cf98e0aab6
Status: Downloaded newer image for jwigley/smokeping-speedtest:latest

**standard_init_linux.go:211: exec user process caused "exec format error"**

─────────────────────────────────────────────────────
 DietPi v6.33.3 : 20:17 - Sat 21/11/20
 ─────────────────────────────────────────────────────
 - Device model : RPi 3 Model B+ (armv7l)
 - CPU temp : 49'C : 120'F (Optimal temperature)
 - LAN IP : 192.168.1.11 (eth0)
 - MOTD : Take care of yourself and the people around you :)
 ─────────────────────────────────────────────────────
 Architecture |     armv7l
 Temperature  |     48'C : 118'F (Optimal temperature)
 Governor     |     ondemand
 Throttle up  |     85% CPU usage

                 Current Freq    Min Freq   Max Freq
 CPU0         |      1400 MHz      600 MHz    1400 MHz
 CPU1         |      1400 MHz      600 MHz    1400 MHz
 CPU2         |      1400 MHz      600 MHz    1400 MHz
 CPU3         |      1400 MHz      600 MHz    1400 MHz

**Comment by jwigley** [comment]
Sorry for the late reply.

This is probably something that needs to be looked at in https://github.com/linuxserver/docker-smokeping or the underlying linuxserver base image.

Thanks

**Comment by LSgeo** [comment]
I have the same issue on  Pi 3.
There was a possibly related issue upstream for OrangePi: https://github.com/linuxserver/docker-smokeping/issues/122#issuecomment-1002111660

I executed the command `docker run -d --rm --name=smoketest --tmpfs /config -p 82:80 lscr.io/linuxserver/smokeping:latest` on my Pi 3, and it worked - I can access docker-smokeping on port 82 as configured.

It might be an issue with speedtest-cli, but I couldn't see anything easy.  I'm just going to use an x86 pc instead of the pi.
