### ISSUE TITLE
Speed test is not running reliably at 60 minute intervals.

### ISSUE THREAD

**Issue by pbrubaker** [jwigley/docker-smokeping-speedtest#21]
Hey there.  First, thanks for this great image.  Worked perfectly (mostly) on a Synology DS1522+ NAS.

However, I'm having some issues with download/upload speed tests.  I have the interval set to 3600 seconds, and sometimes I don't get any data.  Does Ookla limit the number of tests in a time period or day?  I searched and I wasn't able to find any information indicating so.

Does the speed test write a log anywhere to help diagnose this?

![image](https://user-images.githubusercontent.com/6944373/210449024-cafb793d-ad9e-4115-8756-b33109c9c79d.png)

**Comment by jwigley** [comment]
I'm not sure of any Ookla limits, but I do have my interval set to the same 3600s and haven't run into this.

The speedtest cli can take a --debug arg which makes the output much more verbose.
By default I don't think smokeping logs probe outputs, but maybe that can be configured.

If not though, you could at least manually run the cli from inside the container with the --debug arg.
```
/usr/local/bin/speedtest-cli --secure --debug
```

**Comment by pbrubaker** [comment]
Cool, I'll give that a shot and let you know how it goes.  I appreciate the quick repsonse!
