### ISSUE TITLE
speedtest-cli targets changing

### ISSUE THREAD

**Issue by relaxteb** [jwigley/docker-smokeping-speedtest#31]
when running a manual speedtest-cli --list some server id's appear. When used in the target file the smokeping fails. When running again speedtest-cli --list, the serverlist has changed.

**Comment by relaxteb** [comment]
I've found this article which might be the case? https://www.reddit.com/r/commandline/comments/x2hv2o/speedtestcli_list_returns_only_10_servers/

**Comment by relaxteb** [comment]
also very low speeds are reported in the RRDTool, running speedtest-cli manually improves the speed. When using speedtest-tracker a more real bandwidth is reached

**Comment by jwigley** [comment]
> when running a manual speedtest-cli --list some server id's appear. When used in the target file the smokeping fails. When running again speedtest-cli --list, the serverlist has changed.

From memory, I think `--list` lists the closest 10 servers, so it might not always be the same. As long as your server id is valid though it shouldn't matter if it's in the list. When you ran it manually did specifying `--server` work?

I have added support for the official ookla cli in https://github.com/jwigley/docker-smokeping-speedtest/pull/33, if you want to give that a go.

> also very low speeds are reported in the RRDTool, running speedtest-cli manually improves the speed. When using speedtest-tracker a more real bandwidth is reached

I vaguely remember a discussion around this before. It's possible there's some performance limitation with running speedtest-cli inside a container. My internet is only 100Mbps, so might explain why I haven't run into it.

**Comment by relaxteb** [comment]
Specifying --server did work, however it seems the server id sometimes dissappears and can not be used again. 
The Ookla CLI works and immediately gives proper speeds. Tnx!

**Comment by relaxteb** [comment]
Is is also possible to change the RRD Graph units from Ms to Mb/s? As in a custom configuration?
