### ISSUE TITLE
Long shot here, but I wonder if it's possible to use fast-cli rather than speedtest?

### ISSUE THREAD

**Issue by jaxjexjox** [jwigley/docker-smokeping-speedtest#37]
Hey @jwigley 

Apologies for badgering you! -  I'm googling and not seeing anything regarding a fast-cli probe for Smokeping, so it's probably a long shot but I'd be curious to try fast-cli rather than speedtest-cli.

Do you know if this is even possible?   

Thanks for your time, really appreciate the hard work.

**Comment by jwigley** [comment]
I had a quick look too and think you're right in that there isn't currently a fast-cli probe.

If there was one though, I don't think it'd be too much effort to add support for it in this docker image. Creating the probe itself is where most of the work is. If the fast-cli input and output is similar to speedtest-cli's then you probably could use the original smokeping probe (https://github.com/mad-ady/smokeping-speedtest/blob/master/speedtest.pm) as a base to hack on.

Thanks,

**Comment by jaxjexjox** [comment]
> I had a quick look too and think you're right in that there isn't currently a fast-cli probe.
> 
> If there was one though, I don't think it'd be too much effort to add support for it in this docker image. Creating the probe itself is where most of the work is. If the fast-cli input and output is similar to speedtest-cli's then you probably could use the original smokeping probe (https://github.com/mad-ady/smokeping-speedtest/blob/master/speedtest.pm) as a base to hack on.
> 
> Thanks,


I suspect I've not got the skills to be honest.   I could try but it may be difficult.   
I have found another container which I've found easy to run ,but I've not figured out how to install fast directly into your container (yet) -  I'll need to learn how to build docker images, which I've only done once before, honestly I ought to learn this.


https://hub.docker.com/r/mschirrmeister/fast-cli   - worked with --upload and --single-line        though the output of it is a bit fancy and not clean.

Then there's this, which supports json output but I feel like that's also not ideal
https://github.com/sindresorhus/fast-cli


Finally (and no offense is intended, I know you didn't write smokeping itself)
I actually prefer these 2 tools for speed test tracking and plotting than smokeping - but editing smokeping looked the easiest to work with the probs and targets file.

https://github.com/ansemjo/speedtest-plotter
https://hub.docker.com/r/henrywhitaker3/speedtest-tracker


I shall continue to fiddle with what's out there, see what I can figure out.
(if only speedtest-cli could be forced to 443 or 80, the mandatory requirement of 8080 makes it impossible to use in the environment I'm trying to use it in!)
